### ISSUE TITLE
error while using the ImapClient.GetMessages() method, 

### ISSUE THREAD

**Issue by cherkaoui-mouad** [bertjohnson/OpaqueMail#38]
each time I try to use the method I have an error specifying that the input string is in an incorrect format, the first time I've used the named parameters to resolve the issue, but just after some test I found that the problem persist and, whether i'm using any of the overloads of the method I still have the same message error, 

var mails = _client.GetMessages(folderName, 30, 0, false, false, false); 

it was correctly working before,

**Comment by bertjohnson** [comment]
Hi, sorry to hear about your error.  Could you provide a little more detail?

1. You mentioned it worked before -- do you know which version number you were previously testing with?

2. Does the mailbox / folder name you're working with have any special characters or spaces?

3. Could you post the exception details?

As soon as there's more detail, I'll take a look.  Thanks.

**Comment by cherkaoui-mouad** [comment]
Version: 2.1.5
MailboxName: "Inbox"
InnerException Message: {"Input string was not in a correct format."}
Stacktrace: 
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Byte.Parse(String s, NumberStyles style, NumberFormatInfo info)
   at OpaqueMail.Net.Functions.FromQuotedPrintable(String input, String charSet, Encoding encoding)
   at OpaqueMail.Net.Functions.Decode(String input, String contentTransferEncoding, String charSet, Encoding encoding)
   at OpaqueMail.Net.MailMessage..ctor(String messageText, MailMessageProcessingFlags processingFlags, Boolean parseExtendedHeaders)
   at OpaqueMail.Net.MailMessage..ctor(String messageText, MailMessageProcessingFlags processingFlags)
   at OpaqueMail.Net.ImapClient.<GetMessageHelper>d__156.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OpaqueMail.Net.ImapClient.<GetMessagesAsync>d__9d.MoveNext()


TargetSite: 
{Void StringToNumber(System.String, System.Globalization.NumberStyles, NumberBuffer ByRef, System.Globalization.NumberFormatInfo, Boolean)}

**Comment by bertjohnson** [comment]
Thanks for the detail.  It looks like there's a malformed quoted-printable encoding in one or more of your messages.  If so, that would be independent of the version of OpaqueMail.  It's just ephemeral and sometimes mis-encoded messages pop up.

Would you be able to help test by doing the following?

1. Try selecting any other mailbox/folder and checking for similar issues.  If those occur in several folders, this might be a bigger issue.  If not, it may be isolated to a single message.
2. Try doing the following to silently handle the error in the "FromQuotedPrintable()" method in Functions.cs:
  1. At line 710, add an open "try{" block.
  2. After "return outputBuilder.ToString()", close the `try` with "} catch (Exception) { return input; }".
  3. Test it out and see if messages come through.  Then view each, checking if any are malformed / non-decoded.

Please let me know if you have any luck with that approach.  If so, it may be best to return a non-decodable string as-is.  I'll look into that for the next release.

If you do locate the problematic message, please feel free to forward to [bert@opaquemail.org](bert@opaquemail.org) and I'll troubleshoot.  Thanks again.

**Comment by bertjohnson** [comment]
With version 2.2.4, I've added fallback behavior so malformed "quoted-printable" encodings return the input string instead of throwing an exception.
