### ISSUE TITLE
.GetMessages() - Index and length must refer to a location within the string.\r\nParameter name: length

### ISSUE THREAD

**Issue by karaliolio** [bertjohnson/OpaqueMail#41]
Hi, I was using the code in the tutorials with my gmail mail box and I got this error:
Index and length must refer to a location within the string.\r\nParameter name: length

Here is the code where I get the error:
List<MailMessage> recentMessages = await imapClient.GetMessagesAsync("Inbox", 50);

Here is some more info:
   at System.String.Substring(Int32 startIndex, Int32 length)
   at OpaqueMail.ImapClient.<GetMessageHelper>d__190.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OpaqueMail.ImapClient.<GetMessagesAsync>d__151.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OpaqueMail.ImapClient.<GetMessagesAsync>d__148.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

When I try to get 2 mails instead of 50 everything is OK. I guess there is an email that is breaking the code. Maybe the problem is in the body of the email, because when I set headersOnly = true, no exception is thrown.

**Comment by bertjohnson** [comment]
Thanks karaliolio.  Indeed, it sounds like a malformed MIME message can't be parsed and that is causing the error.  I realize this is a late response and you may have moved on.  If you still have a specific email that causes issues, please attach it or forward it to bert AT opaquemail DOT org and I'll take a look.
